### Register a new user
POST http://localhost:8080/api/register
Content-Type: application/json

{
    "name": "Gideon Bature",
    "email": "gideonbat@me.com",
    "password": "password",
    "department": "Computer Science",
    "courseOfStudy": "Computer Science",
    "level": "100",
    "type": "tutor"
}

### Login
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "gideonbat@me.com",
    "password": "password"
}

### Get all users

GET http://localhost:8080/api/users
consent-type: application/json
Authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NGVjMjVhZWQ2NTVlNTE5YzM3Y2U4OSIsInR5cGUiOiJ0dXRvciIsImlhdCI6MTcxNjQzNzY0NiwiZXhwIjoxNzE2NTI0MDQ2fQ.TWmY03-R8TfVQFzQeTmellD-nLFKsXfNnnQE_frHKpI"

{
    "type": "tutor",
    "department": "Computer Science",
}